version: '3.8'
services:
  app:
    build: .
    volumes:
      - .:/app
      - ./nginx/certs:/certs
    ports:
      - "9876:9876"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWD: ${DB_PASSWD}
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${DB_PASSWD}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWD}
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app 
volumes:
  db_data:
