#!/bin/bash

#ΓΙΑ ΕΣΑΣ AYTO ΒΓΑΛΤΕ TO ΑΠΟ COMMENT 
#python3 cli.py "$@"

#ΓΙΑ ΕΣΑΣ AYTO ΒΑΛΤΕ TO ΣΕ COMMENT 
python cli.py "$@"

#this code exists so that we can run the CLI as requested
# which is:
#$ se2342 scope --param1 value1 [--param2 value2 ...] --format fff

#!! Προς το παρόν δουλεύει και τρέχει ως εξής:
#$ ./se2342 scope --param1 value1 [--param2 value2 ...] --format fff

#if this does not exist then we run it as such:
#$ python cli.py scope --param1 value1 [--param2 value2 ...] --format fff