#!/bin/bash

#If the Python commands are running in the environment with 'python3', remove the following command from comments.
python3 cli.py "$@"

#If the Python commands are running in the environment with 'python', remove the following command from comments.
#python cli.py "$@"

#this code exists so that we can run the CLI as requested which is:
#$ se2342 scope --param1 value1 [--param2 value2 ...] --format fff

#if this does not exist then we run it as such:
#$ python cli.py scope --param1 value1 [--param2 value2 ...] --format fff